### ISSUE TITLE
Possible useful Media/Assets

### ISSUE THREAD

**Issue by asimone** [surged20/wjmais#1]
1.) This is fantastic and I will be adding it to [laughingbeholder.com](https://laughingbeholder.com/) the first chance I'll get.

2.) There is definitely stuff on laughing beholder that might have some relevance to this effort. You are welcome to use anything I made and I'm happy to connect you with the creators I've highlighted on this site if you think that would be helpful.

**Comment by surged20** [comment]
That's fantastic! Thanks for the offer, I'll take a look. I definitely want to enhance the module with any content that can be redistributed with proper attribution.

**Comment by asimone** [comment]
There is also a discord of people who are currently converting all old school monsters to 5e. https://discord.gg/jYu5EDdy

**Comment by surged20** [comment]
Added to notes and joined the discord server. Thanks!
