### ISSUE TITLE
[BUG]Minor changes to ship items breaks them / editing items moves them to "cargo"

### ISSUE THREAD

**Issue by UnoriginalDM** [surged20/wjmais#10]
When you make changes within ship items like change rarity, change equipment type, and many of the other fillable fields, the item will lose its type and no longer work properly within the ship sheet. Preferably, the DM should be able to control the type of item (module, hull, upgrades, weapons) on the details page.
![image](https://user-images.githubusercontent.com/77896718/136667640-fd8071e0-b274-4f34-bdfb-097512ea29bc.png)
![image](https://user-images.githubusercontent.com/77896718/136667657-5cdef877-2c0a-48b9-bddf-ec1398f5993f.png)

EDIT: I am also noticing that if you open and edit an item WITHOUT changing anything and close the item it moves into cargo as well.
![image](https://user-images.githubusercontent.com/77896718/136667957-cedb8bcd-b60f-48db-aae1-ae1ac4fcc504.png)
![image](https://user-images.githubusercontent.com/77896718/136667975-db67ec73-cc91-494d-bdd2-53412799267e.png)
![image](https://user-images.githubusercontent.com/77896718/136668001-82eeaec8-a853-40bb-8c26-ec6cadfe3f7b.png)

I am using the latest 5e 1.5.2 and latest WJMAIS.

**Comment by surged20** [comment]
Thanks for the report. This bug should be fixed in release 0.3.1. Let me know if you still have this issue.

**Comment by UnoriginalDM** [comment]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOH SNAAAAAAAAAP MY PLAYERS ARE GONNA BE PUMMMMMPPPPEDDD THAT SPELLJAMMER SHIP BATTLES ARE BACK ON

But for real I will keep you posted. Thanks for your hard work.

**Comment by UnoriginalDM** [comment]
Hey so I finally had sometime to mess around and it appears to still be happening for any items that are Modules, Hulls, or Upgrades.

**Comment by surged20** [comment]
> Hey so I finally had sometime to mess around and it appears to still be happening for any items that are Modules, Hulls, or Upgrades.

Ok, first off, thank you for taking the time to provide detailed screenshots that is very helpful. Unfortunately I just walked through these examples again and can't recreate it. I'm on Core 9.255, dnd5e 1.5.7, and wjmais 0.3.1.

Can you do the following:
1. confirm core, system, and wjmais versions
2. open your browser developers tools with F12 and note any errors there
3. export a broken ship and attach to this issue so I can inspect it. 
![2022-03-11_16-07](https://user-images.githubusercontent.com/71271408/157966955-285e976b-aa2c-48ea-aeb5-761bd7117de1.png)

**Comment by surged20** [comment]
> Hey so I finally had sometime to mess around and it appears to still be happening for any items that are Modules, Hulls, or Upgrades.

Ignore my request. This is my bad. The fix commit didn't get pushed up but the changelog did. The latest release (0.3.2) now contains the fix I've been using so please update and try again.

**Comment by UnoriginalDM** [comment]
Hey happy to report that the issue is fixed. Thanks a bunch dude.

**Comment by surged20** [comment]
Happy to have it addressed finally, thanks for confirming.
