### ISSUE TITLE
Display ship movement template

### ISSUE THREAD

**Issue by surged20** [surged20/wjmais#18]
Display a contextual WJ cone of movement template on demand.

This would probably be best managed with a toggle hot key and placed relative to current token position and rotation.

**Comment by UnoriginalDM** [comment]
Hello,

I see you added this in the latest patch. Very helpful. One slight request would be the ability to set an offset or default starting direction (0°, 90°, etc) for the templates facing. This is not the most crucial of things. I could always rotate my own tokens eventually or can always just rotate the template in game as well but it would be nice to have for custom tokens outside of the ones that come with the module.
![image](https://user-images.githubusercontent.com/77896718/188273080-edd8b379-2297-4032-82d5-2296b413716a.png)

Once again thank you for all your hard work. Myself and players appreciate you brining wildjammer to foundryvtt.

**Comment by surged20** [comment]
Ok, so if I understand your token image isn't oriented the way Foundry expects it to be? That is, Foundry assumes a token image is facing down by default (corresponding to 0°). Just making sure that's what I'm seeing on your custom token image on the left. I've personally just rotated some other token images I use (top-down tokens I prefer) in an external image processing app to match Foundry's token orientation expectations.

**Comment by UnoriginalDM** [comment]
Ooooh. I've been using foundry forever and never knew downwards was consider 0°. That makes sense.

I will rotate my tokens using GIMP.

Thanks again my dude.

**Comment by surged20** [comment]
Excellent. Yeah, that's why the Forgotten Adventures top-down tokens included with the dnd5e system are always oriented facing down/south when they are dropped in. A bit of trivia...the measured template orientation does not match token orientation, the measured template orientation is 0° being to the right. So this feature is compensating for that when checking rotation and placing the movement template.

You're welcome!

**Comment by surged20** [comment]
Implemented in 0.6.x
