### ISSUE TITLE
Font overrides other character sheet modules

### ISSUE THREAD

**Issue by Gilokius** [surged20/wjmais#19]
When Wildjammer is enabled, the font on other sheets, such as https://foundryvtt.com/packages/compact-beyond-5e-sheet, is overridden. I use a custom UI with fonts I prefer to the default, which makes this particularly jarring.
Without Wildjammer enabled:
<img width="432" alt="Screenshot 2022-08-16 214318" src="https://user-images.githubusercontent.com/62490757/185016208-1b653785-3e65-4b91-b5d3-80a222f47903.png">
With Wildjammer enabled:
<img width="445" alt="Screenshot 2022-08-16 214418" src="https://user-images.githubusercontent.com/62490757/185016205-a045ec20-9532-4cc3-9d20-8721af07f22f.png">

**Comment by surged20** [comment]
I've got a fix on the v10 branch for this. Will pull into a v9 maintenance release.

**Comment by surged20** [comment]
I added a fix to the 0.4.3 release. Please update let me know if it resolves the problem for you.

**Comment by surged20** [comment]
Fixed in v9/0.4.3 and v10/0.5.0
