### ISSUE TITLE
[BUG] Cannot open "Default Token Configuration" Core Settings

### ISSUE THREAD

**Issue by UnoriginalDM** [surged20/wjmais#21]
Hey Surged hope things are well.

There is a slight bug in the module that prevents the core setting "Default Token Configuration" from opening.

![image](https://user-images.githubusercontent.com/77896718/201479836-7c34517f-8296-453a-84ce-880e395e8894.png)
![image](https://user-images.githubusercontent.com/77896718/201479772-e900c6c6-d000-469f-ab6a-4cdc8898aef4.png)

**Comment by surged20** [comment]
Thanks for the report. Fixed in 0.8.2.
