### ISSUE TITLE
Unusual option in Features Section.

### ISSUE THREAD

**Issue by RocketGamerPie** [surged20/wjmais#22]
![Wildjammer Sheet](https://user-images.githubusercontent.com/125320872/221967610-0a42180d-bee9-4e8a-a9f9-b947b76e67c8.jpg)

I'm not certain if this is a bug or an issue on my end. I see this option on the Wildjammer sheet. I'm using Foundry V10.291. And only have LibWrapper and Wildjammer active at the moment for modules.

**Comment by surged20** [comment]
Bug. Translation issue. Will be fixed next release.

**Comment by surged20** [comment]
Fixed in 0.8.1
