### ISSUE TITLE
Price of cargo is [object Object]

### ISSUE THREAD

**Issue by tprussak** [surged20/wjmais#23]
Using 5e system version 2.1.5, Foundry v10.291, Librwapper 1.12.12.0, Wildjammer v0.8.2, all items in the Cargo section have their prices listed as [object Object]. I can reproduce with only these modules enabled.

This is due to 5e version 2.1.0, which changed the way price data is handled:

"Price Data
Price data for Items has changed from a single value to an object with value, and denomination properties."
https://github.com/foundryvtt/dnd5e/releases/tag/release-2.1.0

A quick fix for this is replacing the price block on line 1216 of wjmais.js with:
```
          {
            label: game.i18n.localize("DND5E.Price"),
            css: "item-price",
            property: "system.price.value",
            editable: "Number",
          },
          {
            label: "Denomination",
            css: "item-denomination",
            property: "system.price.denomination",
          },
```

I don't think there is localization set up for denomination.

**Comment by surged20** [comment]
Thanks for the report and suggested change! I used the above as is except adding a wjmais localization for denomination in 1fa36ee. Fixed in release 0.9.3.
