### ISSUE TITLE
Wildjammer quick reference option

### ISSUE THREAD

**Issue by mclearc** [surged20/wjmais#25]
Would it be possible to set some other means for toggling the quick reference sheet? I use the minimal UI module, which also uses the Foundry logo for toggling, and it would be great to be able to disable the WJ Foundry logo option and have another option for the WJ reference sheet, either via an icon or (more preferably for me) via some hotkey.

**Comment by surged20** [comment]
Sure, I added a keybind in 3ad2cd9e9b509121a9f6f45b7414c8970d69720f and released 0.9.4 with this feature.
