### ISSUE TITLE
Features tab of Wildjammer vehicles sheets is not interactable

### ISSUE THREAD

**Issue by BestTeaMaker** [surged20/wjmais#27]
![image](https://github.com/surged20/wjmais/assets/25994079/a59d2a6a-37aa-4f34-b8e8-88c520a9d89d)

The entire features tab cannot be interacted with in the way it's supposed to be. If you try and drag anything from the items compendium from Wildjammers, it does not populate this tab at all and instead sits in the Cargo & Crew list instead. 

![image](https://github.com/surged20/wjmais/assets/25994079/5512c69b-8a55-4ace-995d-a325ef96d118)

The only thing that can be added are Features, but even with that, the items cannot be moved or deleted at all. You also can't edit things as well as those buttons remain unresponsive.

Also, check the ships in the compendium, and those with pre-established features like the Tradesman, and those too have their pre-set modules like figureheads stuck in the Cargo tab as well.

![image](https://github.com/surged20/wjmais/assets/25994079/ce2a12ce-75b0-448c-82a4-1fe83924835a)

**Comment by BSDungeonmaster** [comment]
This may be connected to a loss the the expanded "Weapon Properties" Wildjammer injected into Dnd5e to classify the objects. Screenshot of the Medium Ballista included below, where you can see it used to include further info, like crew count.

Game System Version: Dnd5e 3.0
Foundry Version: 11 Stable Build 350

![Screenshot 2024-02-12 101355](https://github.com/surged20/wjmais/assets/159798119/2f5dabe4-d653-4e5d-8259-d13fae9ede02)

**Comment by surged20** [comment]
Also being addressed. I have a couple more bugs that were identified in the process to wrap up and should likely have an update out in the next week.

**Comment by BSDungeonmaster** [comment]
> Also being addressed. I have a couple more bugs that were identified in the process to wrap up and should likely have an update out in the next week.

Glad to hear you are still supporting this project, I look forward to it!

**Comment by MightyMushka** [comment]
Agreed; this module is invaluable for my Spelljammer campaign so hopefully those pesky bugs are squashed soon :) Thanks!

**Comment by surged20** [comment]
Fixed in https://github.com/surged20/wjmais/releases/tag/1.0.1
