### ISSUE TITLE
Cannot delete characters from Bridge Crew Roles

### ISSUE THREAD

**Issue by BestTeaMaker** [surged20/wjmais#28]
![image](https://github.com/surged20/wjmais/assets/25994079/ba39a726-3bb4-4245-af03-6de66e45280e)

The delete button simply doesn't work. I can remove all people with the NPC Ship checkbox, but I'd like to not have to do that to remove people.

**Comment by surged20** [comment]
This is being addressed in a forthcoming set of fixes for dnd5e 3.x.x.

**Comment by surged20** [comment]
Fixed in https://github.com/surged20/wjmais/releases/tag/1.0.1

**Comment by surged20** [comment]
Fixed in https://github.com/surged20/wjmais/releases/tag/1.0.1
