### ISSUE TITLE
Wildjammer Error Preparing Actor Sheets

### ISSUE THREAD

**Issue by BSDungeonmaster** [surged20/wjmais#29]
Hello,

While Wildjammer is installed and activated, I cannot view any character sheets (even those not associated with the mod). When loading foundry, an "error detected in module" notification directs me to check the JS console. It appears that for every actor:

"Could not prepare data  [Actor Name] TypeError: CONFIG.WJMAIS is undefined"

As an example, 

Could not prepare data  Nevezen & Udachi TypeError: CONFIG.WJMAIS is undefined
    patchRollData patch.js:120
    call_wrapper libWrapper-wrapper.js:616
    getRollData DAESystem.js:166
    getRollData DAEdnd5e.js:1065
    call_wrapper libWrapper-wrapper.js:616
    getRollData#0 libWrapper-wrapper.js:189
    prepareDerivedData actor.mjs:162
    prepareData foundry.js:14212
    prepareData flags.mjs:21
    prepareData actor.mjs:131
    call_wrapped libWrapper-wrapper.js:507
    prepareData DAEdnd5e.js:1139
    call_wrapper libWrapper-wrapper.js:616
    prepareData#0 libWrapper-wrapper.js:189
    _safePrepareData foundry.js:14187
    _initialize foundry.js:14015
    DataModel commons.js:6919
    Document commons.js:7583
    BaseActor commons.js:9244
    ClientDocument foundry.js:13979
    Actor foundry.js:18605
    <anonymous> flags.mjs:6
    <anonymous> document.mjs:8
    Actor5e actor.mjs:16
    applyDelta commons.js:9159
    apply foundry.js:18412
    _createSyntheticActor foundry.js:18475
    _configure foundry.js:18387
    DataModel commons.js:6913
    Document commons.js:7583
    BaseActorDelta commons.js:9073
    ClientDocument foundry.js:13979
    ActorDelta foundry.js:18383
    initialize commons.js:12606
    get actor foundry.js:24881
    tokensOnScenes migrations.js:105
    getSequencerEffectTokens migrations.js:31
    getSequencerEffectTokens migrations.js:29
    getSequencerEffectTokens migrations.js:25
    0 migrations.js:102
    runMigrations migrations.js:11
    <anonymous> module.js:65
    #call foundry.js:730
    callAll foundry.js:687
    setupGame foundry.js:8746
DAEdnd5e.js:1177:17

**Comment by slayer1551** [comment]
Same here, disabling the module and foundry character sheet works fine

**Comment by jboyle1013** [comment]
Same here

**Comment by CaptainCurso** [comment]
I am also experiencing the same issue. Removing the module fixed it.

**Comment by jboyle1013** [comment]
So. the issue here appears to be that this module is not compatible with the character sheets for dnd5e 3.1.x
i got it to work on a system running dnd 5e 3.0, but not on 3.1, so there is a workaround rn if you want.

**Comment by surged20** [comment]
Fixed in https://github.com/surged20/wjmais/releases/tag/1.0.1
